"""create table diagnose and diagnose_detail

Revision ID: 8f83d131a7ac
Revises: 7cc62ec43184
Create Date: 2024-03-07 03:23:25.502101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f83d131a7ac'
down_revision: Union[str, None] = '7cc62ec43184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnose_details',
    sa.Column('dia_detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dia_id', sa.Integer(), nullable=True),
    sa.Column('tumor_number', sa.Integer(), nullable=True),
    sa.Column('tumor_size', sa.Float(), nullable=True),
    sa.Column('washout', sa.Boolean(), nullable=True),
    sa.Column('capsule', sa.Boolean(), nullable=True),
    sa.Column('threshold_growth', sa.Boolean(), nullable=True),
    sa.Column('APHE', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dia_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('dia_detail_id')
    )
    op.create_table('diagnoses',
    sa.Column('dia_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dia_detail_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('ai_lr', sa.String(length=255), nullable=True),
    sa.Column('doctor_lr', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dia_detail_id'], ['diagnose_details.dia_detail_id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['pid'], ['patients.pid'], ),
    sa.PrimaryKeyConstraint('dia_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnoses')
    op.drop_table('diagnose_details')
    # ### end Alembic commands ###
