"""create update column

Revision ID: c1567718e220
Revises: d98d185adc62
Create Date: 2024-03-07 03:21:35.466226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1567718e220'
down_revision: Union[str, None] = 'd98d185adc62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('license_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('payment_detail_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'payments', 'licenses', ['license_id'], ['license_id'])
    op.create_foreign_key(None, 'payments', 'payment_details', ['payment_detail_id'], ['payment_detail_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'payment_detail_id')
    op.drop_column('payments', 'license_id')
    # ### end Alembic commands ###
